-- PHASE 1 —EXPLORATORY ANALYSIS 
-- total revenue generated by the food delivery analysis
SELECT SUM(order_amount - discount) AS total_revenue FROM orders;

--Total Orders Per City
SELECT r.city, COUNT(*) AS total_orders
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.city
ORDER BY total_orders DESC;

---Top 10 Customers by Spending
SELECT c.customer_id, c.name, c.city, SUM(o.order_amount - o.discount) AS total_spending
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.name, c.city
ORDER BY total_spending DESC
LIMIT 10;

-- PHASE 2 — CUSTOMER SEGMENTATION

---- Customer Category (Gold/Silver/Bronze)
SELECT c.customer_id, c.name, c.city,
       SUM(o.order_amount - o.discount) AS total_spending,
       CASE 
           WHEN SUM(o.order_amount - o.discount) >= 5000 THEN 'Gold'
           WHEN SUM(o.order_amount - o.discount) >= 2000 THEN 'Silver'
           ELSE 'Bronze'
       END AS customer_category
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.name, c.city
ORDER BY total_spending DESC;

--PHASE 3 — RESTAURANT PERFORMANCE 
--Top 10 Restaurants by Revenue
SELECT r.restaurant_id, r.restaurant_name, r.city,
       SUM(o.order_amount - o.discount) AS total_revenue,
       COUNT(o.order_id) AS total_orders
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name, r.city
ORDER BY total_revenue DESC
LIMIT 10;

--6 Average Rating vs Revenue
SELECT r.rating, 
       COUNT(DISTINCT r.restaurant_id) AS num_restaurants,
       SUM(o.order_amount - o.discount) AS total_rating_revenue,
       SUM(o.order_amount - o.discount) / COUNT(DISTINCT r.restaurant_id) AS avg_revenue_per_restaurant
FROM restaurants r
LEFT JOIN orders o ON r.restaurant_id = o.restaurant_id
GROUP BY r.rating
ORDER BY r.rating DESC;


-- -PHASE 4 — DELIVERY ANALYSIS
-- 7 Average Delivery Time Per City
SELECT r.city, AVG(o.delivery_time) AS avg_delivery_time
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.city
ORDER BY avg_delivery_time;

--8 Late Deliveries (Above 45 Minutes)
SELECT r.city, COUNT(*) AS late_deliveries
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
WHERE o.delivery_time > 45
GROUP BY r.city
ORDER BY late_deliveries ASC;

-- PHASE 5 — PAYMENT & DISCOUNT ANALYSIS

-- 9 Payment Method Distribution
SELECT payment_method, COUNT(*) AS count
FROM orders
GROUP BY payment_method
ORDER BY count DESC;

-- 10 Discount Impact on Revenue
SELECT 
    CASE 
        WHEN discount > 0 THEN 'With Discount'
        ELSE 'Without Discount'
    END AS discount_status,
    COUNT(*) AS order_count,
    SUM(order_amount) AS total_revenue,
    SUM(order_amount - discount) AS revenue_after_discount
FROM orders
GROUP BY discount_status
ORDER BY revenue_after_discount DESC;


---ADVANCED SQL --
--11 Monthly Revenue Using CTE
WITH Monthly_Revenue AS (
    SELECT 
        DATE_FORMAT(order_date, '%Y-%m') AS month,
        SUM(total_amount - discount_amount) AS total_revenue,
        COUNT(*) AS total_orders
    FROM orders
    GROUP BY DATE_FORMAT(order_date, '%Y-%m')
)
SELECT month, total_revenue, total_orders
FROM Monthly_Revenue
ORDER BY month DESC;

-- 12 Rank Restaurants by Revenue (Window Function)
SELECT r.restaurant_id, r.restaurant_name, r.city,
       SUM(o.order_amount - o.discount) AS total_revenue,
       RANK() OVER (ORDER BY SUM(o.order_amount - o.discount) DESC) AS revenue_rank
FROM orders o
JOIN restaurants r ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name, r.city
ORDER BY revenue_rank;

---13 Above Average Revenue Restaurants (Subquery)

WITH restaurant_revenue AS (
    SELECT r.restaurant_id, r.restaurant_name,
           SUM(o.order_amount - o.discount) AS total_revenue
    FROM orders o
    JOIN restaurants r ON o.restaurant_id = r.restaurant_id
    GROUP BY r.restaurant_id, r.restaurant_name
)
SELECT restaurant_id, restaurant_name, total_revenue
FROM restaurant_revenue
WHERE total_revenue > (SELECT AVG(total_revenue) FROM restaurant_revenue)
ORDER BY total_revenue DESC;

-- phaseDATABASE OBJECTS
-- 14 Create Revenue View
CREATE VIEW restaurant_revenue_view AS
SELECT r.restaurant_id, r.restaurant_name, r.city,
       SUM(o.order_amount - o.discount) AS total_revenue
    FROM orders o
    JOIN restaurants r ON o.restaurant_id = r.restaurant_id
    GROUP BY r.restaurant_id, r.restaurant_name, r.city;

-- 15 Top N Restaurants Query
SELECT restaurant_id, restaurant_name, city, total_revenue
FROM restaurant_revenue_view
ORDER BY total_revenue DESC
LIMIT 10;

-- PHASE 8-- Performance Optimization
 --16 Index on order_date (for monthly reports)

CREATE INDEX idx_order_date ON orders(order_date);

-- 17 Index on customer name (for customer search queries)
CREATE INDEX idx_customer_name ON customers(name);


-- 18 Index on restaurant_name
CREATE INDEX idx_restaurant_name ON restaurants(restaurant_name);

-- PHASE 9 — Automation Logic
-- 19 Create high_value_orders table
CREATE TABLE high_value_orders (
    log_id INT PRIMARY KEY AUTO_INCREMENT,
    order_id INT,
    restaurant_id INT,
    customer_id INT,
    order_amount DECIMAL(10,2),
    log_time datetime DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER after_order_insert
AFTER INSERT ON orders
FOR EACH ROW
BEGIN
    IF NEW.order_amount > 1000 THEN
        INSERT INTO high_value_orders (order_id, restaurant_id, customer_id, order_amount)
        VALUES (NEW.order_id, NEW.restaurant_id, NEW.customer_id, NEW.order_amount);
    END IF;
END;

insert into orders values(1010, 138, 231, '2024-01-01', 1200.00, 100.00, 'Credit Card', 30);


-- TRIGGER 1 —  20 Prevent Negative Discount 
CREATE TRIGGER before_order_insert
BEFORE INSERT ON orders
FOR EACH ROW
BEGIN
    IF NEW.discount < 0 THEN
      set NEW.discount = 0;
    END IF;
END;

insert into orders values(1014, 138, 231, '2024-01-01', 1200.00, -50.00, 'Credit Card', 30);
select * from orders where order_id = 1014;

---  21 delivery delay warning 
create table delivery_delay_log (
    log_id INT PRIMARY KEY AUTO_INCREMENT,
    order_id INT,
    restaurant_id INT,
    customer_id INT,
    delivery_time INT,
    created timestamp DEFAULT CURRENT_TIMESTAMP
);

create trigger log_delivery_delay
AFTER INSERT ON orders
FOR EACH ROW
BEGIN
    IF NEW.delivery_time > 45 THEN
        INSERT INTO delivery_delay_log (order_id, restaurant_id, customer_id, delivery_time)
        VALUES (NEW.order_id, NEW.restaurant_id, NEW.customer_id, NEW.delivery_time);
    END IF;
END;

insert into orders values(1015, 138, 231, '2024-01-01', 1200.00, 100.00, 'Credit Card', 50);
select * from delivery_delay_log where order_id = 1015;




